version: '3.8'
services:
  app:
    build: .
    container_name: amigos_ecom_app_c
    image: app_amigos_ecom
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    container_name: db_c
    image: postgres:12
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db:
    driver: local
